import { func_numberAnimations } from '$utils/animated-numbers';
import { autoClickOnFirst } from '$utils/auto-click-on-first';
import { categoryTitleUpdater } from '$utils/category-title-updater';
import { coloredGridPattern } from '$utils/colored-grid-pattern';
import { loadFinsweetAttributes } from '$utils/finsweet-attributes-loader';
import { heroLightboxVideo } from '$utils/hero-lightbox-video';
import { func_leadershipPageHeight } from '$utils/leadership-page-height';
import { func_popupOverlayHandler } from '$utils/popup-overlay-handler';
import { loadSharerScript } from '$utils/sharer-loader';
import { func_spanCircles } from '$utils/span-circles';
import { func_yearChanger } from '$utils/year-changer';
import { func_compareTableHeight } from '$utils/compare-table-height';
import { glossaryHandler } from '$utils/glossary-handler';
import { faqCategoryOrganizer } from '$utils/faq-category-organizer';
import { hubspotFormPlaceholders } from '$utils/hubspot-form-placeholders';
import { hubspotFormPlaceholders_v2 } from '$utils/hubspot-form-placeholders_v2';

window.Webflow ||= [];
window.Webflow.push(() => {
  loadFinsweetAttributes();
  autoClickOnFirst();
  categoryTitleUpdater();
  heroLightboxVideo();
  coloredGridPattern();
  func_popupOverlayHandler();
  func_yearChanger();
  func_numberAnimations();
  func_spanCircles();
  func_leadershipPageHeight();
  func_compareTableHeight();
  loadSharerScript();
  glossaryHandler();
  faqCategoryOrganizer();
  hubspotFormPlaceholders();
  hubspotFormPlaceholders_v2();
});
